#!/usr/bin/env bash
set -eu

declare -r working_directory=$1
declare -a terraform_args=()

if [[ ! -d "$working_directory" ]]; then
	echo >&2 "ERROR: working directory not found: $1"
	exit 2
fi


terraform() {
	echo >&2 "DEBUG: running 'terraform $*' ..."
	#command terraform "$@"
}

terraform_args+=(init -input=false)


[[ -n "${RD_CONFIG_LOCK:-}" ]] && terraform_args+=(-lock=$RD_CONFIG_LOCK)
[[ -n "${RD_CONFIG_LOCK_TIMEOUT:-}" ]] && terraform_args+=(-lock-timeout=$RD_CONFIG_LOCK_TIMEOUT)
[[ -n "${RD_CONFIG_BACKEND_CONFIG:-}" ]] && terraform_args+=(-backend-config=$RD_CONFIG_BACKEND_CONFIG)

cd "$working_directory" || exit 2

terraform "${terraform_args[@]}"

# Simulated output
cat <<'EOF'
Terraform has been successfully initialized!"
EOF

exit $?