#!/usr/bin/env bash
set -eu

declare -r working_directory=$1 subcommand=$2
declare -a terraform_args=()

if [[ ! -d "$working_directory" ]]; then
	echo >&2 "ERROR: working directory not found: $1"
	exit 2
fi

terraform_args+=(workspace "$subcommand")

[[ -n "${RD_CONFIG_STATE:-}" ]] && terraform_args+=(-state "$RD_CONFIG_STATE")
[[ -n "${RD_CONFIG_NAME:-}" ]]  && terraform_args+=("$RD_CONFIG_NAME")

# Import the terraform wrapper function
. "$(dirname "$0")/terraform"

cd "$working_directory" || exit 2
terraform "${terraform_args[@]}"

if [[ "${TERRAFORM_DRYRUN:-}" == true ]]
then
# Simulated output
cat <<'EOF'
EOF
fi
exit $?